### ISSUE TITLE
Requires npm install for plugin to work, then alters CSS properties via Browserify

### ISSUE THREAD

**Issue by KayBeSee** [Retsly/ampersand-autocomplete-view#1]
Hey --

I'm having an issue where I `npm install ampersand-autocomplete-view` but then get an error about how module `css-browserify` cannot be found. When I go into the ampersand-autocomplete-view directory and npm install it (which I usually don't have to do with other modules), the error goes away but then my CSS gets highjacked by a `<style>` element placed in my application's header.

Any idea how I can prevent this behavior from happening?

**Comment by RongxinZhang** [comment]
@KayBeSee This is Rongxin from Retsly. Thank you for bringing this up. We are looking into it. Are you integrating with Retsly or this a non-related project?

**Comment by RongxinZhang** [comment]
@KayBeSee this should fix your problem. 
- I will have to get it approved before publishing to npm
https://github.com/Retsly/ampersand-autocomplete-view/pull/2/files
- However, you can try this fix: `npm install git://github.com/Retsly/ampersand-autocomplete-view.git#rongxin/css-require` in your local github repo.

**Comment by EnFinlay** [comment]
Fixed with #2, closing this issue.
